### ISSUE TITLE
Branch `rule-id` and condition are missing from response

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/hs-backend-booster#536] opened 2024-03-04 10:39 UTC
Related:
* runtimeverification/haskell-backend#3716
* runtimeverification/pyk#942

As of runtimeverification/haskell-backend#3716  `kore-rpc` returns an optional `rule-id` along with an optional `rule-substitution` and `rule-predicate`.  Ensure that the Booster returns the same data on branching.

Tests: runtimeverification/pyk#942.

**Comment by geo2a** [comment] 2024-03-05 09:22
This is a duplicate of https://github.com/runtimeverification/hs-backend-booster/issues/499, we'll try to prioritize

**Closed** 2024-04-03 11:03 UTC
