### ISSUE TITLE
kore-rpc-booster uses all memory and dies

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/hs-backend-booster#445] opened 2023-12-21 11:15 UTC
At some step in our proof, the `kore-rpc-booster` server starts allocating memory until it uses everything and dies. It allocates more than 100G.

I tried running the server with `-l Simplify`, but it displays no messages while allocating memory (it displays some normal-looking simplification messages before that).

Bug report:
[infinite-loop.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/13740660/infinite-loop.tar.gz)

**Comment by virgil-serbanuta** [comment] 2023-12-21 21:50
FWIW, I'm not sure if the problem here is in the booster backend itself, or the problem is that the booster does not provide enough information to figure out what is happening.

**Comment by jberthold** [comment] 2024-01-08 04:27
I took a quick look into what is happening in this request. First findings:
* It is indeed the `kore-rpc` simplificaiton that appears to loop and allocates all available memory. This can be double-checked by running the server with `--no-post-exec-simplify` (the request will succeed) 
* The result obtained from this execute request is a json file of 1.12 GB (when formatted). 
* Most of this size is taken up by a cell map in path `foundry.mandos.elrond.node.callState.wasm.mainStore`

**Comment by jberthold** [comment] 2024-01-08 05:41
Interestingly, the `-l SimplifyKore` option (to log simplification attempts in the `kore-rpc` code) does not show any output while the process allocates all available memory.

Also, I was able to determine that the elrond configuration together with just _one_ constraint `1000 <Int ARG_0` is causing the issue. Attaching [a state file in .gz format](https://github.com/runtimeverification/hs-backend-booster/files/13856534/state-only-predicate-5.json.gz) that causes the issue when sent in a `simplify` request.

.

**Comment by virgil-serbanuta** [comment] 2024-01-08 15:37
Not sure if it's useful, but I'll try to provide some context: the `mainStore` cell contains part of the WASM virtual machine state.

Most likely, the largest part of it (by far) is the `funcs` cell, which contains ~400 function definitions.

The next in size is likely to be the `mems` cell, which contains the VM memory. Usually this is less than 4 MB in size (when printed as k/json/whatever), but when we hit cases that are not handled by the current simplification rules, it can grow a lot. I guess that could also happen if the Booster backend does not apply some of the simplification rules, but that is unlikely to matter for this issue anyway.

The `mainStore` cell also contains the `globals` cell which contains global variables and should be rather small, and a few other cells which should not matter at all.

**Comment by Baltoli** [comment] 2024-01-10 10:26
@virgil-serbanuta to take a look at minimising the input to the simplify request to see if the issue can be reproduced with a smaller input - it will then be easier for @jberthold et. al. to look at profiling what's happening.

**Comment by virgil-serbanuta** [comment] 2024-01-10 19:36
I think that this bug report will generate much smaller execute requests:
[infinite-loop.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/13892191/infinite-loop.tar.gz)

**Comment by virgil-serbanuta** [comment] 2024-01-15 18:05
@jberthold In order to not be stuck, I tried to split the non-working proof in two, the second part is starting shortly after the OOM above (I'm setting up things by hand). However, this second proof failed in a similar way toward its end (after a tens of thousands of steps), so I'm stuck again.

**Comment by geo2a** [comment] 2024-01-16 15:40
I did two things today:
* isolated a simplify request from the latest bug report: 
[002_request.json](https://github.com/runtimeverification/hs-backend-booster/files/13952516/002_request.json)
* attempted to generate GHC heap profiles

So far the results are inconclusive. We see a huge `THUNK_2_0` that I think is a tuple thunk, but I did not manage to track down where is it actually coming from. I'm trying to make an info table profile.

**Comment by geo2a** [comment] 2024-01-16 21:17
Attaching an info table profile of `kore-rpc`, unfortunately quite inconclusive as well 
![kore-rpc-distinct-constructor-tables](https://github.com/runtimeverification/hs-backend-booster/assets/8296326/979a7285-b00c-439a-942b-eda6d7667c2b) --- rename to `.html`

**Comment by jberthold** [comment] 2024-01-16 23:59
> Attaching an info table profile of `kore-rpc`, unfortunately quite inconclusive as well ![kore-rpc-distinct-constructor-tables](https://private-user-images.githubusercontent.com/8296326/297191266-979a7285-b00c-439a-942b-eda6d7667c2b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NDIxOTEsIm5iZiI6MTcwNTQ0MTg5MSwicGF0aCI6Ii84Mjk2MzI2LzI5NzE5MTI2Ni05NzlhNzI4NS1iMDBjLTQzOWEtOTQyYi1lZGE2ZDc2NjdjMmIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMjE1MTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY3MTE4MWJlNDlhMzc2OWFkYzNhZWMwYmYyMzk1NmM0MzJhNzE5MTcxN2RkMjhlZDY2NzdmOTgyMGE4NzE5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pSOSWmcoVLpyyXO64TnfWyh3nRaYbDAHy3Gxrln3ymg) --- rename to `.html`

o/t: Very strange, I could not access the linked file (the link points to `...private-user-images.githubusercontent.com`) but I could access it through the link in the email I got :man_shrugging:

**Comment by jberthold** [comment] 2024-01-18 06:11
I found the place where the memory explodes... it's the `INT.pow` hook, making efforts to compute `2 ^ 34359738368` (which is quite heroic, I guess)

My trace has some degree of context (by logging equations with `--log-entries DebugAttemptEquation` in `kore-rpc`, equivalent to `-l SimplifyKore` in booster):
```
    applying equation at /tmp/kbuild-kmxwasm-semantics-m9i4tva3/kmxwasm-semantics/include/kmxwasm-semantics/lemmas/int-inequalities-lemmas.md:285:8-286:42 to term:
        /* T Fn D Spa */
        Lbl'Unds-LT-'Int'Unds'{}(
            /* T Fn D Sfa */
            Lbllog2IntTotal{}(/* T Fn D Sfa */ ConfigVarARG'Unds'0:SortInt{}),
            /* T Fn D Sfa Cl */ \dv{SortInt{}}("34359738368")
        )
Context:
    (DebugAttemptEquation) while applying equation at /tmp/kbuild-kmxwasm-semantics-m9i4tva3/wasm-semantics/include/wasm-semantics/kwasm-lemmas.md:289:10-289:140
        (DebugAttemptEquation) while applying equation at /mnt/data/runtime-verification/k/k-distribution/target/release/k/include/kframework/builtin/domains.md:1352:8-1352:59
            (DebugAttemptEquation) while applying equation at /tmp/kbuild-kmxwasm-semantics-m9i4tva3/kmxwasm-semantics/include/kmxwasm-semantics/lemmas/int-inequalities-lemmas.md:285:8-286:42
```
So there seems to be a "simplification" that rewrites `log2IntTotal(ARG) <Int N => ARG <Int 2 ^ N`, could that be?

**Comment by virgil-serbanuta** [comment] 2024-01-18 12:33
That's probably it, thanks.

**Comment by Baltoli** [comment] 2024-01-25 16:42
Closing for now @virgil-serbanuta! Thanks for confirming

**Closed by Baltoli** 2024-01-25 16:42 UTC
