### ISSUE TITLE
Server crashes on vacuous step

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/hs-backend-booster#471] opened 2024-01-18 16:15 UTC
Booster crashes when executing a rule of the form 

```
rule 0 => 1 ensures false
```

Bug report: [bug-report.zip](https://github.com/runtimeverification/hs-backend-booster/files/13978992/bug-report.zip)

Reproduction in `pyk` (with K version: v6.1.83):

```
$ make test-integration TEST_ARGS='-n0 -k test_execute_booster[vacuous]'
```

**Comment by jberthold** [comment] 2024-01-18 23:51
I was unable to reproduce the crash with the provided `bug-report.zip`. Both `kore-rpc-booster` and `booster-dev` (as of master at the time of writing) return a `vacuous` response with `3 ~> .K` in the `k` cell as the final state.

**Comment by jberthold** [comment] 2024-01-19 00:42
OK, correction: the above (observing the segfault) was with an earlier version of `booster`, not with current `main`.
Tme current `main` (d153e54) follows a change to the LLVM backend, which apparently already landed in K framework, but without the companion change to `booster` being in K framework.
Will see that we update the K dependency ASAP and investigate how to avoid this with more tests on upgrade PRs.

**Comment by jberthold** [comment] 2024-01-19 01:58
https://github.com/runtimeverification/k/pull/3911 should fix this , please re-test it with an update K version and re-open if the problem persists

**Closed by jberthold** 2024-01-19 01:58 UTC
Labels: bug
