### ISSUE TITLE
Booster crash: custom hooked `Map` is stripped of the element sort after LLVM simplification

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/hs-backend-booster#321] opened 2023-09-29 13:49 UTC
I have a query that makes the booster backend stop with an error, while it works when querying the Haskell backend directly.

Bug report: [bug-report.zip](https://github.com/runtimeverification/hs-backend-booster/files/12765678/bug-report.zip)

Output:
```
...
[Info#proxy] Starting RPC server
[Info] Process request 1 execute
[Info#proxy] Starting execute request
[Rewrite] Stopped after 0 steps. @(hs-backend-booster-0.0.0-DpKnlYxxzPeBfB7OJwCE7f:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:559:18)
[Rewrite] No rules applicable for the pattern Term:
...
Conditions:
    \equalsTerm{}(_<=Int_("0", VarARG_0:SortInt{}), "true") @(hs-backend-booster-0.0.0-DpKnlYxxzPeBfB7OJwCE7f:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:559:18)
[Rewrite] Applied simplification @(hs-backend-booster-0.0.0-DpKnlYxxzPeBfB7OJwCE7f:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:559:18)
[Rewrite] Retrying with simplified pattern @(hs-backend-booster-0.0.0-DpKnlYxxzPeBfB7OJwCE7f:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:559:18)
[Rewrite] Stopped after 0 steps. @(hs-backend-booster-0.0.0-DpKnlYxxzPeBfB7OJwCE7f:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:559:18)
[Rewrite] No rules applicable for the pattern Term:
...
Conditions:
    \equalsTerm{}(_<=Int_("0", VarARG_0:SortInt{}), "true") @(hs-backend-booster-0.0.0-DpKnlYxxzPeBfB7OJwCE7f:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:559:18)
[Info#proxy] Booster Stuck at Depth {getNat = 0}
[Info#proxy] Simplifying booster state and falling back to Kore 
[Info#proxy] Simplifying execution state
[Info#booster] Simplifying a pattern
[Warn#proxy] Unexpected failure when calling Kore simplifier, returning original term
```

Also, I'm getting this python stack trace + error:
```
Traceback (most recent call last):
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 742, in _request
    return self._client.request(method, **params)
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 238, in request
    return self._default_client.request(method, **params)
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 315, in request
    self._check(data)
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 327, in _check
    raise JsonRpcError(**response['error'])
pyk.kore.rpc.JsonRpcError: Could not verify pattern

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/data/runtime-verification/elrond-wasm-real-elrond/kmxwasm/src/kmxwasm/property.py", line 337, in <module>
    main(sys.argv[1:])
  File "/mnt/data/runtime-verification/elrond-wasm-real-elrond/kmxwasm/src/kmxwasm/property.py", line 333, in main
    action.run()
  File "/mnt/data/runtime-verification/elrond-wasm-real-elrond/kmxwasm/src/kmxwasm/property.py", line 133, in run
    raise result.exception
  File "/mnt/data/runtime-verification/elrond-wasm-real-elrond/kmxwasm/src/kmxwasm/property_testing/running.py", line 147, in run_claim
    tools.explorer.extend(
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 390, in extend
    _is_vacuous, depth, cterm, next_cterms, next_node_logs = self.cterm_execute(
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 81, in cterm_execute
    er = self._kore_client.execute(
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 782, in execute
    result = self._request('execute', **params)
  File "/home/virgil/.cache/pypoetry/virtualenvs/kmxwasm-CAf7Hewu-py3.10/lib/python3.10/site-packages/pyk/kore/rpc.py", line 745, in _request
    raise KoreClientError(message=err.message, code=err.code, data=err.data) from err
pyk.kore.rpc.KoreClientError: Could not verify pattern
code= 2
message= Could not verify pattern
data= {'context': ['\\and (<unknown location>)', "symbol or alias 'Lbl'-LT-'generatedTop'-GT-'' (<unknown location>)", "symbol or alias 'Lbl'-LT-'foundry'-GT-'' (<unknown location>)", "symbol or alias 'Lbl'-LT-'mandos'-GT-'' (<unknown location>)", "symbol or alias 'Lbl'-LT-'elrond'-GT-'' (<unknown location>)", "symbol or alias 'Lbl'-LT-'node'-GT-'' (<unknown location>)", "symbol or alias 'Lbl'-LT-'callState'-GT-'' (<unknown location>)", "symbol or alias 'Lbl'-LT-'wasm'-GT-'' (<unknown location>)", "symbol or alias 'Lbl'-LT-'instrs'-GT-'' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'kseq' (<unknown location>)", "symbol or alias 'inj' (<unknown location>)", "symbol or alias 'Lblframe'UndsUndsUndsUndsUnds'WASM'Unds'Frame'Unds'Int'Unds'ValTypes'Unds'ValStack'Unds'MapIntToVal' (<unknown location>)", "symbol or alias 'Lbl'Unds'MapIntToVal'Unds'' (<unknown location>)", "symbol or alias 'Lbl'Unds'Int2Val'Pipe'-'-GT-Unds'' (<unknown location>)", '(/mnt/data/runtime-verification/elrond-wasm-real-elrond/.kbuild/kmxwasm-semantics/0a9b8db/target/v6.0.108-0-g33a37fee9f-dirty/haskell/definition.kore 1215:71, <unknown location>)'], 'error': 'Expecting sort SortVal{} but got SortKItem{}.'}
```

**Comment by virgil-serbanuta** [comment] 2023-11-02 21:03
Here is one such map: https://github.com/runtimeverification/wasm-semantics/blob/master/data/map-int-to-int.k

**Comment by geo2a** [comment] 2023-11-10 12:48
Steps to reproduce in the `mx-backend` repository:

Build the semantics:

```
<checkout mx-backend>
git checkout booster-issue-321
git submodule update --init
cd kmxwasm/k-src/mx-semantics/
git checkout booster-issue-321
git submodule update --init
cd deps/wasm-semantics/
git checkout booster-issue-321
cd ../../..
kbuild kompile llvm-library
```

Run the proof:
```
cd kmxwasm
poetry run python3 -m src.kmxwasm.property \
    --claim src/tests/integration/data/test_change_quorum-int2val-spec.json \
    --kcfg=../.property/kcfg.json \
    --booster
```

This should produce an error ending with:
```
'error': 'Expecting sort SortVal{} but got SortKItem{}.'
```

**Comment by geo2a** [comment] 2023-11-14 15:03
I've managed to get much closer to the problem, and it's not what we though it was. Looks like the problem manifests when we apply the `init_local` rule with concrete arguments, which invokes the `MapIntToVal:primitiveUpdate` function rule from the `MAP-INT-TO-VAL-PRIMITIVE-CONCRETE` module. This is a concrete module and the function is sent tothe  LLVM backend for evaluation. I guess the LLVM backend does not play well with the custom hooked map and slaps an injection into `KItem` in top of the elements. When the resulting term is attempted to be re-internalized in Booster, we get the sorting error above.

**Comment by geo2a** [comment] 2023-11-14 21:25
Seems related: https://github.com/runtimeverification/llvm-backend/issues/788

**Comment by geo2a** [comment] 2023-11-14 21:26
@virgil-serbanuta we'll need to bring somebody who actively works on the LLVM backend to advise. @Baltoli could you have a look?

**Comment by Baltoli** [comment] 2023-11-15 08:38
https://github.com/runtimeverification/llvm-backend/issues/788 is indeed related; I think this is the same underlying problem - thanks for the reminder @geo2a. I will need to remind myself of the solution again as it's been a while since I looked at it, but as I recall the gist of it is for us to implement a new set of collection hooks in the backend that behave correctly with respect to sorting in this way.

**Comment by jberthold** [comment] 2023-11-23 11:18
Workaround has been merged (correcting the sorts of updated maps from the LLVM backend). Awaiting fix from LLVM backend library.

**Comment by goodlyrottenapple** [comment] 2023-12-11 15:30
I've confirmed that with the latest k version, removing our injection fix works for the unit test we originally added to test this behaviour. Do we want to revert the injection fix or leave it in case someone still uses an old version of the llvm-backend?

**Comment by Baltoli** [comment] 2023-12-11 15:41
Revert your fix, I think - we shouldn't generally be in the habit of supporting old releases in that way.

**Closed** 2023-12-12 09:53 UTC
Labels: bug
